name: CI with Gradle

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACTION_TOKEN }}
          submodules: recursive

      - name: Filtering changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            application:
            - 'build.gradle'
            - 'src/**'

      - name: Set up JDK 21
        if: steps.changes.outputs.application == 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle with cache
        if: steps.changes.outputs.application == 'true'
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        if: steps.changes.outputs.application == 'true'
        run: chmod +x gradlew

      - name: Check for application-local.properties
        if: steps.changes.outputs.application == 'true'
        run: |
          if [ ! -f 2025-1-SBConfig/application-local.properties ]; then
            echo "❌ 설정 파일이 누락되었습니다: 2025-1-SBConfig/application-local.properties"
            exit 1
          fi

      - name: Build with Gradle Wrapper
        if: steps.changes.outputs.application == 'true'
        run: ./gradlew build -x test
        env:
          SPRING_PROFILES_ACTIVE: local

  code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Filtering changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            application:
            - 'build.gradle'
            - 'src/**'

      - name: Set up JDK 21
        if: steps.changes.outputs.application == 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle with cache
        if: steps.changes.outputs.application == 'true'
        uses: gradle/actions/setup-gradle@v3

      - name: Style check
        if: steps.changes.outputs.application == 'true'
        run: ./gradlew spotlessCheck --console=plain